### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ItzAmirreza** [tomkeuper/BedWars2023#311]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BedWars2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Plugin/Server Incompatibility

### What happened?

This randomply appears.

[12:37:16 WARN]: Exception in thread "Craft Scheduler Thread - 94" org.apache.commons.lang.UnhandledException: Plugin BWProxy2023 v1.0 generated an exception while executing task 47
[12:37:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(Carbon:57)
[12:37:16 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(Carbon:23)
[12:37:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:37:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:37:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[12:37:16 WARN]: Caused by: java.util.ConcurrentModificationException
[12:37:16 WARN]:        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
[12:37:16 WARN]:        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
[12:37:16 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1054)
[12:37:16 WARN]:        at com.tomkeuper.bedwars.proxy.arenamanager.ArenaManager.getArena(ArenaManager.java:41)
[12:37:16 WARN]:        at com.tomkeuper.bedwars.proxy.connectionmanager.redis.RetrieveArenaTask.run(RetrieveArenaTask.java:35)
[12:37:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(Carbon:64)
[12:37:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(Carbon:53)
[12:37:16 WARN]:        ... 4 more

### Expected Behaviour

This should not appear.

### How to Reproduce

server version 1.8.8 paper 
velocity
bwproxy2024
connect to Redis for BUNGEE mode

check the console

### Console Log

https://pastebin.com/syzzhZui

### Errors

https://pastebin.com/syzzhZui

### Additional Info

Here is the video of /bw join solo not working as it should (feels like plugin doesn't have the player count data? might be because of this error)

https://cdn.discordapp.com/attachments/760851293379624982/1260574221478924350/Rec_0001.mp4?ex=668fd0ba&is=668e7f3a&hm=7719058d74c1952389562e71511cf5f90885a05c6ef09bdc04518fc7490837e8&

or if it doesn't work
https://discord.com/channels/760851292826107926/760851293379624982/1260574221801619516
in bw23 discord

**Comment by KKiiya** [comment]
Does it interfere with the gameplay? If so, what behaivour does it give

**Comment by KKiiya** [comment]
Also, this error comes from BWProxy2023, next time please use the [BWProxy2023 repository](https://github.com/tomkeuper/BWProxy2023) to report errors coming from it

**Comment by tomkeuper** [comment]
https://github.com/user-attachments/assets/8d01ef5b-66d7-4d8f-a604-9a1f43f4cc6e
