### ISSUE TITLE
Get rid of TAB?

### ISSUE THREAD

**Issue by Stis780** [tomkeuper/BedWars2023#330]
**Is your feature request related to a problem? Please describe.**
https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c

**Describe the solution you'd like**
Remove TAB dependency?

**Describe alternatives you've considered**
Previous fork had implementation that didn't require TAB?

**Additional context**
```
[20:27:46 WARN]: [BedWars2023] Task #21 for BedWars2023 v1.2.1-SNAPSHOT generated an exception
java.lang.NoClassDefFoundError: me/neznamy/tab/api/nametag/UnlimitedNameTagManager
        at BedWars2023.jar/com.tomkeuper.bedwars.BedWars.lambda$onEnable$20(BedWars.java:723) ~[BedWars2023.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:476) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:327) ~[sakura-1.21.1.jar:1.21.1-DEV-f156073]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.nametag.UnlimitedNameTagManager
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[sakura-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[sakura-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 9 more
[20:27:46 WARN]: com.destroystokyo.paper.exception.ServerSchedulerException: Task #21 for BedWars2023 v1.2.1-SNAPSHOT generated an exception
[20:27:46 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:487)
[20:27:46 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724)
[20:27:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477)
[20:27:46 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[20:27:46 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305)
[20:27:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:327)
[20:27:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:27:46 WARN]: Caused by: java.lang.NoClassDefFoundError: me/neznamy/tab/api/nametag/UnlimitedNameTagManager
[20:27:46 WARN]:        at BedWars2023.jar//com.tomkeuper.bedwars.BedWars.lambda$onEnable$20(BedWars.java:723)
[20:27:46 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
[20:27:46 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:476)
[20:27:46 WARN]:        ... 6 more
[20:27:46 WARN]: Caused by: java.lang.ClassNotFoundException: me.neznamy.tab.api.nametag.UnlimitedNameTagManager
[20:27:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[20:27:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[20:27:46 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[20:27:46 WARN]:        ... 9 more

```

**Comment by tomkeuper** [comment]
removing tab = no scoreboard + no tab list

if you used the original plugin you should know how buggy it was

**Comment by bandaohana** [comment]
> removing tab = no scoreboard + no tab list
> 
> if you used the original plugin you should know how buggy it was

Would it be possible to support tab-bridge?

**Comment by tomkeuper** [comment]
How does the tab bridge work?

**Comment by bandaohana** [comment]
> How does the tab bridge work?

I would say that it is exactly the same as the normal tab, but its management/configuration is done through the tab on the proxy, and can be on multiple servers.

in other words; scoreboard, tab, nametag/tag...

**Comment by tomkeuper** [comment]
When looking at the features of tab-bridge (https://github.com/NEZNAMY/TAB/wiki/TAB-Bridge) it doesnt look like I can send any scoreboard related info using the bridge so that would mean it doesnt work

**Comment by Stis780** [comment]
I guess the question is if u wanna keep ths updated on leave servers to rot away waiting for plugins to update.

**Comment by tomkeuper** [comment]
Wait for updates on what?

**Comment by bandaohana** [comment]
> When looking at the features of tab-bridge (https://github.com/NEZNAMY/TAB/wiki/TAB-Bridge) it doesnt look like I can send any scoreboard related info using the bridge so that would mean it doesnt work

sorry if I'm being too persistent about this, but it's a recommendation for a future update (or not) in this sense, BW2023 could have an "addon" that would stay on the proxy (velocity or bungee) and send this information to the tab-proxy through a specific port, or the current way in which tab <-> tab-bridge does it

the theory is simple, but writing a code for this makes me a bit "lazy" just thinking about it

**Comment by tomkeuper** [comment]
If someone wants to make an addon for it sure, and im willing to adjust the code of bw2023 for it but I dont have the time to do that myself. I am closing this issue here since its not part of BW2023 itself
